import { Language, AcademicLevel, LessonDepth, SimplicityLevel, LessonFocus } from './types';

// Module Descriptions
export const MODULE_DESCRIPTIONS = {
  [Language.UZ_LATIN]: {
    "default": "Ushbu modul talabalarga soha bo'yicha fundamental bilimlar va amaliy ko'nikmalarni shakllantirishga qaratilgan.",
    "Advokatura": "Advokatura institutining huquqiy maqomi, advokatlarning huquq va majburiyatlari, hamda advokatlik sirini o'rganadi.",
    "Axborot huquqi": "Axborotni izlash, olish, tarqatish va himoya qilish bilan bog'liq ijtimoiy munosabatlarni tartibga soladi.",
    "Davlat va huquq nazariyasi": "Davlat va huquqning kelib chiqishi, mohiyati, funksiyalari va rivojlanish qonuniyatlarini o'rganuvchi fundamental fan.",
    "Fuqarolik huquqi": "Mulkiy va u bilan bog'liq shaxsiy nomulkiy munosabatlarni tartibga soluvchi asosiy xususiy huquq sohasi.",
    "Jinoyat huquqi": "Jinoiy javobgarlik asoslari, jinoyat turlari va jazo tizimini belgilovchi huquq tarmog'i.",
    "Konstitutsiyaviy huquq": "Davlat hokimiyatini tashkil etish va inson huquqlarini ta'minlashning asosiy prinsiplarini belgilaydi.",
    "Xalqaro ommaviy huquq": "Davlatlar va xalqaro tashkilotlar o'rtasidagi siyosiy-huquqiy munosabatlarni tartibga soladi."
  },
  [Language.UZ_CYRILLIC]: {
    "default": "Ушбу модул талабаларга соҳа бўйича фундаментал билимлар ва амалий кўникмаларни шакллантиришга қаратилган.",
    "Адвокатура": "Адвокатура институтининг ҳуқуқий мақоми, адвокатларнинг ҳуқуқ ва мажбуриятлари, ҳамда адвокатлик сирини ўрганади.",
    "Давлат ва ҳуқуқ назарияси": "Давлат ва ҳуқуқнинг келиб чиқиши, моҳияти, функциялари ва ривожланиш қонуниятларини ўрганувчи фундаментал фан.",
    "Фуқаролик ҳуқуқи": "Мулкий ва у билан боғлиқ шахсий номулкий муносабатларни тартибга солувчи асосий хусусий ҳуқуқ соҳаси.",
    "Жиноят ҳуқуқи": "Жиноий жавобгарлик асослари, жиноят турлари ва жазо тизимини белгиловчи ҳуқуқ тармоғи.",
    "Конституциявий ҳуқуқ": "Давлат ҳокимиятини ташкил этиш ва инсон ҳуқуқларини таъминлашнинг асосий принципларини белгилайди."
  },
  [Language.ENGLISH]: {
    "default": "This module is designed to provide students with fundamental knowledge and practical skills in the field.",
    "Advocacy / Bar": "Covers the legal status of the Bar, ethics of advocacy, rights of attorneys, and organization of legal aid.",
    "Theory of State and Law": "Fundamental science studying the origin, development, and functioning of state and law concepts.",
    "Civil Law": "Regulates property and personal non-property relations between private entities.",
    "Criminal Law": "Defines criminal offenses, liability, and the penal system.",
    "Constitutional Law": "Establishes the framework of state power and fundamental human rights.",
    "Public International Law": "Governs relations between states and international organizations."
  },
  [Language.RUSSIAN]: {
    "default": "Этот модуль направлен на формирование у студентов фундаментальных знаний и практических навыков.",
    "Адвокатура": "Изучает правовой статус адвокатуры, права и обязанности адвокатов, а также адвокатскую тайну.",
    "Теория государства и права": "Фундаментальная наука, изучающая происхождение, сущность и закономерности развития государства и права.",
    "Гражданское право": "Отрасль права, регулирующая имущественные и личные неимущественные отношения.",
    "Уголовное право": "Определяет основания уголовной ответственности, виды преступлений и систему наказаний.",
    "Конституционное право": "Закрепляет основы государственного строя и правовой статус личности."
  }
};

// Localized TSUL Modules
export const MODULES_BY_LANGUAGE = {
  [Language.UZ_LATIN]: [
    "Advokatura",
    "Axborot huquqi",
    "Axborot texnologiyalari huquqi",
    "Bank huquqi",
    "Biznes huquqi",
    "Bojxona huquqi",
    "Davlat va huquq nazariyasi",
    "Davlat va huquq tarixi",
    "Ekologiya huquqi",
    "Energetika huquqi",
    "Fuqarolik huquqi",
    "Fuqarolik protsessual huquqi",
    "Huquqiy mantiq",
    "Inson huquqlari",
    "Intellektual mulk huquqi",
    "Investitsiya huquqi",
    "Islom (Musulmon) huquqi",
    "Jinoyat huquqi",
    "Jinoyat protsessual huquqi",
    "Jinoyat-ijroiya huquqi",
    "Konstitutsiyaviy huquq",
    "Korporativ huquq",
    "Kriminalistika",
    "Kriminologiya",
    "Ma'muriy huquq",
    "Ma'muriy protsessual huquq",
    "Mehnat huquqi",
    "Moliya huquqi",
    "Notariat",
    "Oila huquqi",
    "Parlament huquqi",
    "Rim huquqi",
    "Soliq huquqi",
    "Sport huquqi",
    "Sud va huquqni muhofaza qilish organlari",
    "Sug'urta huquqi",
    "Tibbiyot huquqi",
    "Xalqaro biznes huquqi",
    "Xalqaro hakamlik sudlari",
    "Xalqaro ommaviy huquq",
    "Xalqaro xususiy huquq",
    "Yer huquqi"
  ],
  [Language.UZ_CYRILLIC]: [
    "Адвокатура",
    "Ахборот ҳуқуқи",
    "Ахборот технологиялари ҳуқуқи",
    "Банк ҳуқуқи",
    "Бизнес ҳуқуқи",
    "Божхона ҳуқуқи",
    "Давлат ва ҳуқуқ назарияси",
    "Давлат ва ҳуқуқ тарихи",
    "Экология ҳуқуқи",
    "Энергетика ҳуқуқи",
    "Фуқаролик ҳуқуқи",
    "Фуқаролик процессуал ҳуқуқи",
    "Ҳуқуқий мантиқ",
    "Инсон ҳуқуқлари",
    "Интеллектуал мулк ҳуқуқи",
    "Инвестиция ҳуқуқи",
    "Ислом (Мусулмон) ҳуқуқи",
    "Жиноят ҳуқуқи",
    "Жиноят процессуал ҳуқуқи",
    "Жиноят-ижроия ҳуқуқи",
    "Конституциявий ҳуқуқ",
    "Корпоратив ҳуқуқ",
    "Криминалистика",
    "Криминология",
    "Маъмурий ҳуқуқ",
    "Маъмурий процессуал ҳуқуқ",
    "Меҳнат ҳуқуқи",
    "Молия ҳуқуқи",
    "Нотариат",
    "Оила ҳуқуқи",
    "Парламент ҳуқуқи",
    "Рим ҳуқуқи",
    "Солиқ ҳуқуқи",
    "Спорт ҳуқуқи",
    "Суд ва ҳуқуқни муҳофаза қилиш органлари",
    "Суғурта ҳуқуқи",
    "Тиббиёт ҳуқуқи",
    "Халқаро бизнес ҳуқуқи",
    "Халқаро ҳакамлик судлари",
    "Халқаро оммавий ҳуқуқ",
    "Халқаро хусусий ҳуқуқ",
    "Ер ҳуқуқи"
  ],
  [Language.ENGLISH]: [
    "Advocacy / Bar",
    "Information Law",
    "IT Law",
    "Banking Law",
    "Business Law",
    "Customs Law",
    "Theory of State and Law",
    "History of State and Law",
    "Environmental Law",
    "Energy Law",
    "Civil Law",
    "Civil Procedural Law",
    "Legal Logic",
    "Human Rights",
    "Intellectual Property Law",
    "Investment Law",
    "Islamic (Muslim) Law",
    "Criminal Law",
    "Criminal Procedural Law",
    "Penal (Correctional) Law",
    "Constitutional Law",
    "Corporate Law",
    "Criminalistics",
    "Criminology",
    "Administrative Law",
    "Administrative Procedural Law",
    "Labor Law",
    "Financial Law",
    "Notary",
    "Family Law",
    "Parliamentary Law",
    "Roman Law",
    "Tax Law",
    "Sports Law",
    "Judicial and Law Enforcement Agencies",
    "Insurance Law",
    "Medical Law",
    "International Business Law",
    "International Arbitration",
    "Public International Law",
    "Private International Law",
    "Land Law"
  ],
  [Language.RUSSIAN]: [
    "Адвокатура",
    "Информационное право",
    "Право информационных технологий",
    "Банковское право",
    "Бизнес-право",
    "Таможенное право",
    "Теория государства и права",
    "История государства и права",
    "Экологическое право",
    "Энергетическое право",
    "Гражданское право",
    "Гражданское процессуальное право",
    "Юридическая логика",
    "Права человека",
    "Право интеллектуальной собственности",
    "Инвестиционное право",
    "Исламское (Мусульманское) право",
    "Уголовное право",
    "Уголовно-процессуальное право",
    "Уголовно-исполнительное право",
    "Конституционное право",
    "Корпоративное право",
    "Криминалистика",
    "Криминология",
    "Административное право",
    "Административно-процессуальное право",
    "Трудовое право",
    "Финансовое право",
    "Нотариат",
    "Семейное право",
    "Парламентское право",
    "Римское право",
    "Налоговое право",
    "Спортивное право",
    "Судебные и правоохранительные органы",
    "Страховое право",
    "Медицинское право",
    "Международное бизнес-право",
    "Международный арбитраж",
    "Международное публичное право",
    "Международное частное право",
    "Земельное право"
  ]
};

export const TRANSLATIONS = {
  [Language.UZ_LATIN]: {
    brand: "LEARNIFY",
    home: "Bosh sahifa",
    newLesson: "Yangi dars",
    about: "Biz haqimizda",
    configure: "Darsni sozlash",
    configureSubtitle: "Sun'iy intellekt yordamida yaratiladigan yuridik dars parametrlarini sozlang.",
    moduleSection: "Modul va mavzu",
    selectModule: "Modulni tanlang",
    enterTopic: "Dars mavzusini kiriting...",
    academicLevel: "Akademik daraja",
    depth: "Dars chuqurligi",
    style: "O'qitish uslubi",
    simplicity: "Tushuntirish soddaligi",
    simplicityChild: "Menga 10 yoshli boladek tushuntir",
    simplicityStudent: "Universitet talabasi darajasida",
    simplicityResearcher: "Ilmiy tadqiqotchi darajasida",
    lessonFocus: "Darsning asosiy urg'usi",
    structurePref: "Struktura afzalliklari",
    bulletPoints: "Nuqtali ro'yxat",
    tables: "Jadvallar",
    summaries: "Bo'lim xulosalari",
    stepByStep: "Bosqichma-bosqich tushuntirish",
    caseLaw: "Tegishli sud ishlari",
    doctrines: "Huquqiy doktrinalar",
    comparativeAnalysis: "Qiyosiy huquqiy tahlil",
    practicalExercises: "Amaliy kazuslar",
    glossary: "Tayanch iboralar lug'ati",
    bibliography: "Tavsiya etilgan adabiyotlar",
    clean: "Tozalash",
    generate: "Dars yaratish",
    back: "Orqaga",
    objectives: "O'quv maqsadlari",
    concepts: "Asosiy tushunchalar",
    mistakes: "Tez-tez uchraydigan xatolar",
    discussion: "Muhokama savollari",
    conclusion: "Yakuniy xulosa",
    aiTeacher: "AI o'qituvchi",
    aiGreeting: "Salom! Men sun'iy intellekt o'qituvchiman. Ushbu dars bo'yicha savollaringizga javob berishga tayyorman.",
    typeQuestion: "Savolingizni yozing...",
    downloadPdf: "PDF yuklab olish",
    generating: "Dars tayyorlanmoqda...",
    landing: {
      heroTitle: "Yuridik ta'limni sun'iy intellekt bilan o'zgartiring",
      heroSubtitle: "TDYU standartlariga moslashtirilgan birinchi akademik platforma. Soniyalar ichida mukammal darslar, sud ishlari tahlili va huquqiy doktrinalarni o'rganing.",
      cta: "O'qishni boshlash",
      feature1Title: "Akademik aniqlik",
      feature1Text: "TDYU modullari va o'quv dasturiga to'liq moslashtirilgan tuzilma.",
      feature2Title: "AI tahlili",
      feature2Text: "Gemini 3 Pro orqali chuqur yuridik tahlil va keyslar o'rganish.",
      feature3Title: "Ko'p tilli",
      feature3Text: "O'zbek, rus va ingliz tillarida mukammal akademik tarjima.",
    },
    aboutPage: {
      title: "Learnify - kelajak ta'limi",
      subtitle: "Toshkent davlat yuridik universiteti (TDYU) standartlariga moslashtirilgan sun'iy intellekt platformasi.",
      missionTitle: "Bizning missiyamiz",
      missionText: "Yuridik ta'limni raqamlashtirish va talabalarga eng so'nggi pedagogik texnologiyalar yordamida chuqur bilim berish.",
      aiTitle: "AI texnologiyasi",
      aiText: "Google Gemini 3 Pro modellari asosida ishlovchi tizim har bir talabaning ehtiyojiga moslashtirilgan noyob darslarni yaratadi.",
      teamTitle: "Ishlab chiqaruvchi",
      teamText: "Ushbu platforma Oxforder MCHJ tomonidan akademik mukammallik tamoyillari asosida yaratilgan."
    },
    levels: {
      [AcademicLevel.BACHELOR]: "Bakalavr",
      [AcademicLevel.MASTER]: "Magistratura",
      [AcademicLevel.PHD]: "Doktorantura (PhD)",
    },
    depths: {
      [LessonDepth.OVERVIEW]: "Umumiy ko'rish",
      [LessonDepth.STANDARD]: "Standart ma'ruza",
      [LessonDepth.ADVANCED]: "Ilg'or seminar",
    },
    focuses: {
      [LessonFocus.THEORETICAL]: "Nazariy fundamental tahlil",
      [LessonFocus.PRACTICAL]: "Amaliy ko'nikmalar va tatbiq",
      [LessonFocus.CASE_BASED]: "Keyslar tahlili va kazuslar yechimi",
      [LessonFocus.LEGISLATIVE]: "Qonunchilik sharhi va tahlili",
    },
    // Footer translations
    footerTagline: "Kelajak yurisprudensiyasi",
    platform: "PLATFORMA",
    legalDisclaimer: "YURIDIK OGOHLANTIRISH",
    disclaimerText: "Learnify - bu sun'iy intellektga asoslangan akademik yordamchi. Yaratilgan tarkib faqat ma'lumot olish uchun mo'ljallangan va professional yuridik maslahat hisoblanmaydi.",
    copyright: "© 2026 Oxforder MCHJ. Barcha huquqlar himoyalangan.",
    privacyPolicy: "Maxfiylik siyosati",
    termsOfService: "Foydalanish shartlari",
    support: "Qo'llab-quvvatlash",
  },
  [Language.UZ_CYRILLIC]: {
    brand: "LEARNIFY",
    home: "Бош саҳифа",
    newLesson: "Янги дарс",
    about: "Биз ҳақимизда",
    configure: "Дарсни созлаш",
    configureSubtitle: "Сунъий интеллект ёрдамида яратиладиган юридик дарс параметрларини созланг.",
    moduleSection: "Модул ва мавзу",
    selectModule: "Модулни танланг",
    enterTopic: "Дарс мавзусини киритинг...",
    academicLevel: "Академик даража",
    depth: "Дарс чуқурлиги",
    style: "Ўқитиш услуби",
    simplicity: "Тушунтириш соддалиги",
    simplicityChild: "Менга 10 ёшли боладек тушунтир",
    simplicityStudent: "Университет талабаси даражасида",
    simplicityResearcher: "Илмий тадқиқотчи даражасида",
    lessonFocus: "Дарснинг асосий урғуси",
    structurePref: "Структура афзалликлари",
    bulletPoints: "Нуқтали рўйхат",
    tables: "Жадваллар",
    summaries: "Бўлим хулосалари",
    stepByStep: "Босқичма-босқич тушунтириш",
    caseLaw: "Тегишли суд ишлари",
    doctrines: "Ҳуқуқий доктриналар",
    comparativeAnalysis: "Қиёсий ҳуқуқий таҳлил",
    practicalExercises: "Амалий казуслар",
    glossary: "Таянч иборалар луғати",
    bibliography: "Тавсия этилган адабиётлар",
    clean: "Тозалаш",
    generate: "Дарс яратиш",
    back: "Орқага",
    objectives: "Ўқув мақсадлари",
    concepts: "Асосий тушунчалар",
    mistakes: "Тез-тез учрайдиган хатолар",
    discussion: "Муҳокама саволлари",
    conclusion: "Якуний хулоса",
    aiTeacher: "AI ўқитувчи",
    aiGreeting: "Салом! Мен сунъий интеллект ўқитувчиман. Ушбу дарс бўйича саволларингизга жавоб беришга тайёрман.",
    typeQuestion: "Саволингизни ёзинг...",
    downloadPdf: "PDF юклаб олиш",
    generating: "Дарс тайёрланмоқда...",
    landing: {
      heroTitle: "Юридик таълимни сунъий интеллект билан ўзгартиринг",
      heroSubtitle: "ТДЮУ стандартларига мослаштирилган биринчи академик платформа. Сониялар ичида мукаммал дарслар, суд ишлари таҳлили ва ҳуқуқий доктриналарни ўрганинг.",
      cta: "Ўқишни бошлаш",
      feature1Title: "Академик аниқлик",
      feature1Text: "ТДЮУ модуллари ва ўқув дастурига тўлиқ мослаштирилган тузилма.",
      feature2Title: "AI таҳлили",
      feature2Text: "Gemini 3 Pro орқали чуқур юридик таҳлил ва кейслар ўрганиш.",
      feature3Title: "Кўп тилли",
      feature3Text: "Ўзбек, рус ва инглиз тилларида мукаммал академик таржима.",
    },
    aboutPage: {
      title: "Learnify - келажак таълими",
      subtitle: "Тошкент давлат юридик университети (ТДЮУ) стандартларига мослаштирилган сунъий интеллект платформаси.",
      missionTitle: "Бизнинг миссиямиз",
      missionText: "Юридик таълимни рақамлаштириш ва талабаларга энг сўнгги педагогик технологиялар ёрдамида чуқур билим бериш.",
      aiTitle: "AI технологияси",
      aiText: "Google Gemini 3 Pro моделлари асосида ишловчи тизим ҳар бир талабанинг эҳтиёжига мослаштирилган ноёб дарсларни яратади.",
      teamTitle: "Ишлаб чиқарувчи",
      teamText: "Ушбу платформа Oxforder МЧЖ томонидан академик мукаммаллик тамойиллари асосида яратилган."
    },
    levels: {
      [AcademicLevel.BACHELOR]: "Бакалавр",
      [AcademicLevel.MASTER]: "Магистратура",
      [AcademicLevel.PHD]: "Докторантура (PhD)",
    },
    depths: {
      [LessonDepth.OVERVIEW]: "Умумий кўриш",
      [LessonDepth.STANDARD]: "Стандарт маъруза",
      [LessonDepth.ADVANCED]: "Илғор семинар",
    },
    focuses: {
      [LessonFocus.THEORETICAL]: "Назарий фундаментал таҳлил",
      [LessonFocus.PRACTICAL]: "Амалий кўникмалар ва татбиқ",
      [LessonFocus.CASE_BASED]: "Keyslar tahlili va kazuslar yechimi",
      [LessonFocus.LEGISLATIVE]: "Қонунчилик шарҳи ва таҳлили",
    },
    // Footer translations
    footerTagline: "Келажак юриспруденцияси",
    platform: "ПЛАТФОРМА",
    legalDisclaimer: "ЮРИДИК ОГОҲЛАНТИРИШ",
    disclaimerText: "Learnify - бу сунъий интеллектга асосланган академик ёрдамчи. Яратилган таркиб фақат маълумот олиш учун мўлжалланган ва профессионал юридик маслаҳат ҳисобланмайди.",
    copyright: "© 2026 Oxforder МЧЖ. Барча ҳуқуқлар ҳимояланган.",
    privacyPolicy: "Махфийлик сиёсати",
    termsOfService: "Фойдаланиш шартлари",
    support: "Қўллаб-қувватлаш",
  },
  [Language.ENGLISH]: {
    brand: "LEARNIFY",
    home: "Home",
    newLesson: "New Lesson",
    about: "About Us",
    configure: "Configure Lesson",
    configureSubtitle: "Customize the parameters for your AI-generated legal lesson.",
    moduleSection: "Module & Topic",
    selectModule: "Select Module",
    enterTopic: "Enter lesson topic...",
    academicLevel: "Academic Level",
    depth: "Lesson Depth",
    style: "Teaching Style",
    simplicity: "Explanation Simplicity",
    simplicityChild: "Explain like I'm 10 years old",
    simplicityStudent: "Explain as a university student",
    simplicityResearcher: "Explain as a PhD researcher",
    lessonFocus: "Lesson Focus",
    structurePref: "Structure Preferences",
    bulletPoints: "Bullet Points",
    tables: "Tables",
    summaries: "Section Summaries",
    stepByStep: "Step-by-step Explanation",
    caseLaw: "Relevant Case Law",
    doctrines: "Legal Doctrines",
    comparativeAnalysis: "Comparative Analysis",
    practicalExercises: "Practical Exercises",
    glossary: "Glossary of Terms",
    bibliography: "Recommended Reading",
    clean: "Reset",
    generate: "Generate Lesson",
    back: "Back",
    objectives: "Learning Objectives",
    concepts: "Key Concepts",
    mistakes: "Common Mistakes",
    discussion: "Discussion Questions",
    conclusion: "Final Conclusion",
    aiTeacher: "AI Teacher",
    aiGreeting: "Hello! I am your AI Teacher. I am ready to answer your questions about this lesson.",
    typeQuestion: "Type your question...",
    downloadPdf: "Download PDF",
    generating: "Generating Lesson...",
    landing: {
      heroTitle: "Master Law with AI Intelligence",
      heroSubtitle: "The first academic platform dedicated to TSUL students. Generate university-grade lessons, analyze case laws, and master complex legal doctrines in seconds.",
      cta: "Start Learning",
      feature1Title: "Academic Precision",
      feature1Text: "Structure fully aligned with TSUL modules and curriculum standards.",
      feature2Title: "AI Analysis",
      feature2Text: "Deep legal analysis and case studies powered by Gemini 3 Pro.",
      feature3Title: "Multi-lingual",
      feature3Text: "Perfect academic translation in Uzbek, Russian, and English.",
    },
    aboutPage: {
      title: "Learnify - Future of Education",
      subtitle: "Artificial Intelligence platform tailored to Tashkent State University of Law (TSUL) standards.",
      missionTitle: "Our Mission",
      missionText: "To digitize legal education and provide students with deep knowledge using the latest pedagogical technologies.",
      aiTitle: "AI Technology",
      aiText: "Powered by Google Gemini 3 Pro models, the system creates unique lessons tailored to each student's needs.",
      teamTitle: "Developed By",
      teamText: "This platform was created by Oxforder LLC based on principles of academic excellence."
    },
    levels: {
      [AcademicLevel.BACHELOR]: "Bachelor",
      [AcademicLevel.MASTER]: "Master's",
      [AcademicLevel.PHD]: "PhD / Doctorate",
    },
    depths: {
      [LessonDepth.OVERVIEW]: "Overview",
      [LessonDepth.STANDARD]: "Standard Lecture",
      [LessonDepth.ADVANCED]: "Advanced Seminar",
    },
    focuses: {
      [LessonFocus.THEORETICAL]: "Theoretical Fundamental Analysis",
      [LessonFocus.PRACTICAL]: "Practical Skills & Application",
      [LessonFocus.CASE_BASED]: "Case Study & Problem Solving",
      [LessonFocus.LEGISLATIVE]: "Legislative Review & Analysis",
    },
    // Footer translations
    footerTagline: "The Future of Jurisprudence",
    platform: "PLATFORM",
    legalDisclaimer: "LEGAL DISCLAIMER",
    disclaimerText: "Learnify is an AI-powered academic assistant. Generated content is for informational purposes only and does not constitute professional legal advice.",
    copyright: "© 2026 Oxforder LLC. All rights reserved.",
    privacyPolicy: "Privacy Policy",
    termsOfService: "Terms of Use",
    support: "Support",
  },
  [Language.RUSSIAN]: {
    brand: "LEARNIFY",
    home: "Главная",
    newLesson: "Новый урок",
    about: "О нас",
    configure: "Настроить урок",
    configureSubtitle: "Настройте параметры юридического урока, создаваемого искусственным интеллектом.",
    moduleSection: "Модуль и тема",
    selectModule: "Выберите модуль",
    enterTopic: "Введите тему урока...",
    academicLevel: "Академический уровень",
    depth: "Глубина урока",
    style: "Стиль обучения",
    simplicity: "Простота объяснения",
    simplicityChild: "Объясни мне как 10-летнему",
    simplicityStudent: "Объясни как студенту университета",
    simplicityResearcher: "Объясни как аспиранту",
    lessonFocus: "Основной акцент урока",
    structurePref: "Предпочтения по структуре",
    bulletPoints: "Маркированные списки",
    tables: "Таблицы",
    summaries: "Резюме разделов",
    stepByStep: "Пошаговое объяснение",
    caseLaw: "Судебная практика",
    doctrines: "Правовые доктрины",
    comparativeAnalysis: "Сравнительный анализ",
    practicalExercises: "Практические задания",
    glossary: "Глоссарий терминов",
    bibliography: "Рекомендуемая литература",
    clean: "Сбросить",
    generate: "Создать урок",
    back: "Назад",
    objectives: "Учебные цели",
    concepts: "Ключевые понятия",
    mistakes: "Частые ошибки",
    discussion: "Вопросы для обсуждения",
    conclusion: "Заключение",
    aiTeacher: "AI преподаватель",
    aiGreeting: "Привет! Я ваш ИИ-преподаватель. Я готов ответить на ваши вопросы по этому уроку.",
    typeQuestion: "Напишите ваш вопрос...",
    downloadPdf: "Скачать PDF",
    generating: "Создание урока...",
    landing: {
      heroTitle: "Изучайте право с искусственным интеллектом",
      heroSubtitle: "Первая академическая платформа, посвященная студентам ТГЮУ. Создавайте уроки университетского уровня, анализируйте судебную практику и осваивайте сложные правовые доктрины за секунды.",
      cta: "Начать обучение",
      feature1Title: "Академическая точность",
      feature1Text: "Структура полностью соответствует модулям и учебным стандартам ТГЮУ.",
      feature2Title: "AI анализ",
      feature2Text: "Глубокий правовой анализ и изучение кейсов на базе Gemini 3 Pro.",
      feature3Title: "Мультиязычность",
      feature3Text: "Идеальный академический перевод на узбекский, русский и английский языки.",
    },
    aboutPage: {
      title: "Learnify - будущее образования",
      subtitle: "Платформа искусственного интеллекта, адаптированная к стандартам Ташкентского государственного юридического университета (ТГЮУ).",
      missionTitle: "Наша миссия",
      missionText: "Цифровизация юридического образования и предоставление студентам глубоких знаний с использованием новейших педагогических технологий.",
      aiTitle: "Технология ИИ",
      aiText: "Система, работающая на базе моделей Google Gemini 3 Pro, создает уникальные уроки, адаптированные к потребностям каждого студента.",
      teamTitle: "Разработчик",
      teamText: "Платформа создана компанией Oxforder LLC на основе принципов академического совершенства."
    },
    levels: {
      [AcademicLevel.BACHELOR]: "Бакалавр",
      [AcademicLevel.MASTER]: "Магистратура",
      [AcademicLevel.PHD]: "Докторантура (PhD)",
    },
    depths: {
      [LessonDepth.OVERVIEW]: "Обзор",
      [LessonDepth.STANDARD]: "Стандартная лекция",
      [LessonDepth.ADVANCED]: "Продвинутый семинар",
    },
    focuses: {
      [LessonFocus.THEORETICAL]: "Теоретический фундаментальный анализ",
      [LessonFocus.PRACTICAL]: "Практические навыки и применение",
      [LessonFocus.CASE_BASED]: "Разбор кейсов и решение казусов",
      [LessonFocus.LEGISLATIVE]: "Законодательный обзор и анализ",
    },
    // Footer translations
    footerTagline: "Будущее юриспруденции",
    platform: "ПЛАТФОРМА",
    legalDisclaimer: "ПРАВОВАЯ ОГОВОРКА",
    disclaimerText: "Learnify — это академический помощник на базе искусственного интеллекта. Созданный контент предназначен только для информационных целей и не является профессиональной юридической консультацией.",
    copyright: "© 2026 Oxforder LLC. Все права защищены.",
    privacyPolicy: "Политика конфиденциальности",
    termsOfService: "Условия использования",
    support: "Поддержка",
  }
};